language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - pip install -U setuptools
    - python bootstrap.py
    - ./bin/buildout
before_script:
    - ./bin/flake8 mots_vides
script:
    - ./bin/cover
after_success:
    - ./bin/coveralls
notifications:
    irc:
        - "irc.freenode.org#mots-vides"
