"""
Constants for mots-vides
"""
import os

DATA_DIRECTORY = os.path.join(
    os.path.dirname(
        os.path.abspath(__file__)),
    'datas/'
)

LANGUAGE_CODES = {
    'af': 'afrikaans',
    'ar': 'arabic',
    'ast': 'asturian',
    'az': 'azerbaijani',
    'bg': 'bulgarian',
    'be': 'belarusian',
    'bn': 'bengali',
    'br': 'breton',
    'bs': 'bosnian',
    'ca': 'catalan',
    'cs': 'czech',
    'cy': 'welsh',
    'da': 'danish',
    'de': 'german',
    'el': 'greek',
    'en': 'english',
    'eo': 'esperanto',
    'es': 'spanish',
    'et': 'estonian',
    'eu': 'basque',
    'fa': 'persian',
    'fi': 'finnish',
    'fr': 'french',
    'fy': 'frisian',
    'ga': 'irish',
    'gl': 'galician',
    'he': 'hebrew',
    'hi': 'hindi',
    'hr': 'croatian',
    'hu': 'hungarian',
    'hy': 'armenian',
    'ia': 'interlingua',
    'id': 'indonesian',
    'io': 'ido',
    'is': 'icelandic',
    'it': 'italian',
    'ja': 'japanese',
    'ka': 'georgian',
    'kk': 'kazakh',
    'km': 'khmer',
    'kn': 'kannada',
    'ko': 'korean',
    'lb': 'luxembourgish',
    'lt': 'lithuanian',
    'lv': 'latvian',
    'mk': 'macedonian',
    'ml': 'malayalam',
    'mn': 'mongolian',
    'mr': 'marathi',
    'my': 'burmese',
    'nb': 'norwegian',
    'ne': 'nepali',
    'nl': 'dutch',
    'os': 'ossetic',
    'pa': 'punjabi',
    'pl': 'polish',
    'pt': 'portuguese',
    'ro': 'romanian',
    'ru': 'russian',
    'sk': 'slovak',
    'sl': 'slovenian',
    'sq': 'albanian',
    'sr': 'serbian',
    'sv': 'swedish',
    'sw': 'swahili',
    'ta': 'tamil',
    'te': 'telugu',
    'th': 'thai',
    'tr': 'turkish',
    'tt': 'tatar',
    'udm': 'udmurt',
    'uk': 'ukrainian',
    'ur': 'urdu',
    'vi': 'vietnamese',
    'zh': 'chinese',
}
